Ejercicios completos de la semana 3
undefined-academy/semana-3 pull request #102
Opened 2023-04-08 06:55 UTC by DivPanda

2023-04-20 22:37 UTC, StephanyCS1 commented on student-blogs/TeamPanda-5141/blog-index.html
Me parece muy chevere el estilo del blog, la animación de las cards esta lindo
Lo único que cambiaria es el fondo del nav ya que puede llegar hacer un poco molesto con las letras blancas 😁

2023-04-20 22:37 UTC, StephanyCS1 commented on student-cvs/TeamPanda-5141/index.html
El responsive esta super chevere, te recomiendo cambiar el fondo ya que puede ser pesado a la vista

2023-04-20 22:37 UTC, StephanyCS1 commented on student-cvs/TeamPanda-5141/index.html
> +                            href="/semana-3/student-cvs/TeamPanda-5141/form.html">Contáctame 📲</a>
Revisa la url del form porque no me funcionó el botón

2023-04-21 04:48 UTC, DivPanda commented on student-blogs/TeamPanda-5141/blog-index.html
Muchas gracias por todo tu feedback ya me pondré con eso 😊

2023-04-23 01:53 UTC, StephanyCS1 approved these changes

2023-04-26 05:04 UTC, Codemonster808 approved these changes

2023-04-26 05:04 UTC, Codemonster808 approved these changes

2023-04-26 05:04 UTC, Codemonster808 approved these changes

2023-04-26 05:05 UTC, Codemonster808 approved these changes

2023-04-26 05:05 UTC, Codemonster808 approved these changes

2023-04-26 05:06 UTC, Codemonster808 approved these changes

2023-04-26 05:06 UTC, Codemonster808 approved these changes

2023-04-26 05:07 UTC, Codemonster808 approved these changes

2023-04-26 05:07 UTC, Codemonster808 approved these changes

2023-04-26 05:07 UTC, Codemonster808 approved these changes

2023-04-26 05:08 UTC, Codemonster808 approved these changes

2023-04-26 05:08 UTC, Codemonster808 approved these changes

2023-04-26 13:17 UTC, dfm555 requested changes

2023-04-26 13:17 UTC, dfm555 commented on package-lock.json
@DivPanda elimina este archivo

2023-04-26 13:17 UTC, dfm555 commented on package.json
elimina este archivo

2023-04-26 23:48 UTC, DivPanda commented on package-lock.json
### Gracias por el feedback! 🙌🏻 Ya lo borro!

2023-04-27 00:11 UTC, merged