Ejercicios de la semana 3
undefined-academy/semana-3 pull request #103
Opened 2023-04-08 11:04 UTC by carlotagadel

2023-04-19 19:15 UTC, Pancratzia requested changes
Hola! En cuanto al **Blog** veo que has cumplido con todo. Manejaste bien tanto Flex como Grid, y el que sea Responsive le da puntos extra.

En cuanto al **CV** veo que cumple con todo lo solicitado. Muy bien la parte del responsive también.

Finalmente, con respecto al **formulario** has olvidado introducirlo en una carpeta con tu nombre de usuario y lo has dejado en la carpeta de student-forms. Debes crear tu carpeta para que así pueda revisarlo y aprobartelo o revisarlo

2023-04-20 01:34 UTC, yulsdev requested changes
Esta bien, pero en el ejercicio de usar bootstrap o tailwind, no hiciste lo que se pide en el ejercicio. O sea tienes que crear una carpeta con tu nombre de usuario de Discord, dentro de la carpeta `students-forms`

2023-04-21 01:07 UTC, yulsdev approved these changes
Ok

2023-04-21 19:12 UTC, INGCapaDev commented
Buen trabajo, ya corregiste el detalle que te comentaron los compañeros 👍⭐

2023-04-21 19:12 UTC, INGCapaDev approved these changes

2023-04-25 21:06 UTC, Pancratzia commented
Hola! He estado un poco ausente, pero veo que tu proyecto tiene conflictos con el proyecto original. Veo que haz colocado archivos fuera de tus carpetas, lo cual suele suceder. Soluciona dicho conflicto para poder aprobar tu PR y que puedan hacerle el respectivo merge

2023-04-26 19:13 UTC, carlotagadel commented
> Hola! He estado un poco ausente, pero veo que tu proyecto tiene conflictos con el proyecto original. Veo que haz colocado archivos fuera de tus carpetas, lo cual suele suceder. Soluciona dicho conflicto para poder aprobar tu PR y que puedan hacerle el respectivo merge

Hecho!!!

2023-05-01 16:53 UTC, merged