Ejercicios de la semana 3
undefined-academy/semana-3 pull request #104
Opened 2023-04-08 16:52 UTC by Seujumon

Se fue poniendo intenso, pero esta semana sirvió para adelantar un poco. 
En cada ejercicio resolví de formas diferentes. 
1.- Para el Blog traté de comprender la maquetación con Css Grid para la parte del body, y css en lo demás. La página no es responsive, porque no era aún parte de la tarea, pero tengo intenciones de mejorarla. Aproveché otro proyecto personal en el que voy a trabajar en un futuro para motivarme a hacerla. No estoy contento con la elección de la paleta de colores, diseño es algo que aún me toca aprender. 
2.- Para la hoja de vida mantuve la original, que casi era responsive, agregando algunos cambios menores, como sacar las tablas que ya no formaban parte del ejercicio, y los media query, para comenzar a practicar. 
3.- En el caso de bootstrap me tomó más tiempo entender cómo hacer la parte con vite y el package.jason porque quería afianzar la utilidad de cada cosa. Además hay una parte que se hizo durante el ejercicio, agregar el alias, que no encontré en la documentación de bootstrap para 5.3,  quizás la movieron de lugar, aunque si la encontré en la versión anterior, la agregué y como no generaba conflictos, aunque tampoco cambios si no la agregaba, dejé esas lineas. Modifiqué el formulario para que tome los estilos puros implementados por bootstrap, y no quise agregarle css extra porque no era parte de la tarea. Lo mejor de esta actividad, fue que gracias a ver en profundidad la documentación de bootstrap por 3 días, pude entender mejor las grillas y los media query, y espero poder tener tiempo de poner en práctica varias ideas que me surgieron a partir de allí.

2023-04-09 23:15 UTC, Cristhian-Medina requested changes

2023-04-09 23:15 UTC, Cristhian-Medina commented on student-blogs/Seujumon-1612/css/styles.css
> +    /*grid-template-areas: "principal principal principal " "secb secc secd sece";*/
Hola Seujumon,
Una buena práctica es:
- No guardar código comentado en los commit's.
Te recomiendo que revises tu código y elimines todas las líneas comentadas

2023-04-10 02:45 UTC, Seujumon commented on student-blogs/Seujumon-1612/css/styles.css
> +    /*grid-template-areas: "principal principal principal " "secb secc secd sece";*/
Buenísimo, gracias @Cristhian-Medina Ahí lo modifico

2023-04-10 02:53 UTC, Seujumon commented on student-blogs/Seujumon-1612/css/styles.css
> +    /*grid-template-areas: "principal principal principal " "secb secc secd sece";*/
Listo, revisé y actualicé los archivos

2023-04-14 20:01 UTC, JoeOsG approved these changes
### Bien

Solo el boton de contacto quedo el texto fuera del dise.

2023-04-14 20:52 UTC, Seujumon commented
> ### Bien
> 
> Solo el boton de contacto quedo el texto fuera del dise.

Gracias @JoeOsG Voy a revisar lo del botón. Iba a agregarlo como parte de un footer, y di tantas vueltas que no me gustaron que lo terminé dejando solo y después lo desacomodé. Para la siguiente versión voy a armar mejor el footer

2023-04-14 22:20 UTC, merged