Semana 3 (Blog,  responsive CV y form con tailwind
undefined-academy/semana-3 pull request #110
Opened 2023-04-10 19:26 UTC by camilasilvab

Primero estoy trabajando en la maquetación del blog, y continuare subiendo los demás requerimientos para hacer merge. 

El blog no es igual al mostrado en la clase pero busque un layout similar para practicar flexbox y css grid.

2023-05-03 23:48 UTC, JoeOsG approved these changes
### Bien

2023-05-04 15:01 UTC, fedegomezc requested changes
Hola Camila, esta muy bueno tu trabajo. Buen diseño.
Falta el ejercicio de la clase 3. Usar vite como dependencia y agregar el archivo javascript para prevenir el comportamiento por defecto del envío de la información al servidor.
También estaría bueno que en las etiquetas de los formularios uses los atributos correspondientes a cada tipo (type= "email" o  "tel") y agregues 'required' así cuando se hace submit y los datos son incorrectos no hace el envío y pide corregirlo. Y tengo entendido que el botón de submit, debería usar la etiqueta <button type="submit"></button> en lugar de input. Agregando el archivo JavaScript como dice en el punto 3 al enviar el formulario debería salir por consola el "Hola Mundo" que indica dicho código.

2023-05-04 16:16 UTC, camilasilvab commented
> Hola Camila, esta muy bueno tu trabajo. Buen diseño. Falta el ejercicio de la clase 3. Usar vite como dependencia y agregar el archivo javascript para prevenir el comportamiento por defecto del envío de la información al servidor. También estaría bueno que en las etiquetas de los formularios uses los atributos correspondientes a cada tipo (type= "email" o "tel") y agregues 'required' así cuando se hace submit y los datos son incorrectos no hace el envío y pide corregirlo. Y tengo entendido que el botón de submit, debería usar la etiqueta en lugar de input. Agregando el archivo JavaScript como dice en el punto 3 al enviar el formulario debería salir por consola el "Hola Mundo" que indica dicho código.

dd

2023-05-04 17:09 UTC, fedegomezc approved these changes
Perfecto. Cumple con lo requerido

2023-05-04 17:56 UTC, camilasilvab commented on student-forms/CamilaSilva-7352/public/index.html
> +        <input type="text" id="email" placeholder="Enter your email" class="">
que raro en local tengo los cambios pero no subieron en el ultimo commit que hice, voy a revisar la razón.

2023-05-04 21:26 UTC, JoeOsG approved these changes
### Adelante.

2023-05-05 12:55 UTC, merged