actividades semana 3
undefined-academy/semana-3 pull request #115
Opened 2023-04-11 01:34 UTC by brayortepla12

Aportes Pull Request.

💻 Ejercicio
Crear su propio layout de cards que muestre las entradas de su blog usando el layout visto en clase.

💻 Ejercicio
Crear una versión Mobile First Responsive de su hoja de vida (CV).

💻 Ejercicio
Hacer fork del repositorio de la semana-3 https://github.com/undefined-academy/semana-3
Subir la maquetación de la portada de blog usando Flexbox y CSS Grid a la carpeta students-blog.
Subir la maquetación mobile first responsive de la hoja de vida a la carpeta students-cv.
Elegir entre Bootstrap o TailwindCSS y maquetar el formulario de contacto con dicha tecnología en la carpeta student-forms.

2023-04-21 10:42 UTC, Lmendev requested changes
Está muy bueno! Solo dejé un par de comentarios 👏 

Arriba un bot dijo algo, deberías revisarlo también 🤔

2023-04-21 10:42 UTC, Lmendev commented on .vscode/settings.json
> +{
Deberías eliminar este archivo

2023-04-21 10:42 UTC, Lmendev commented on student-cvs/Bryan_Ortega_Plata-1009/src/imagendev-circular-2.png
esta carpeta podría llamarse `img` o `images`, ya que `src` se utiliza por lo general para `sources` como el código fuente de una aplicación

2023-04-21 22:52 UTC, brayortepla12 commented on student-cvs/Bryan_Ortega_Plata-1009/src/imagendev-circular-2.png
ok, muchas gracias ya realizo mis correcciones.

2023-04-21 22:53 UTC, brayortepla12 commented on .vscode/settings.json
> +{
No encuentro como cambiar la etiqueta de "**stale**"

2023-04-22 03:41 UTC, JeronimoCortez approved these changes

2023-04-22 12:26 UTC, brayortepla12 commented on student-cvs/Bryan_Ortega_Plata-1009/src/imagendev-circular-2.png
Listo, esta corregido.
Podrías darle check o approved a el PR para que le hagan merge ?

2023-04-26 03:04 UTC, brayortepla12 commented on student-cvs/Bryan_Ortega_Plata-1009/src/imagendev-circular-2.png
amigo podrías aprobar el PR? @Lmendev

2023-04-26 10:35 UTC, Lmendev requested changes
No lo he podido aprobar porque hay un archivo de configuraciones `.vscode` que no debería estar en el PR 😞

2023-04-26 10:35 UTC, Lmendev commented on .vscode/settings.json
> +{
Hola @brayortepla12 ! 👍 

No has eliminado este archivo del PR

2023-04-26 12:37 UTC, brayortepla12 commented on .vscode/settings.json
> +{
Creo que había entendido mal tu comentario, ahora si eliminé el archivo. revisando me di cuenta de que se fue por error, gracias por la corrección  👍👍

2023-04-28 09:59 UTC, Lmendev approved these changes
Super! 💎

2023-05-02 21:34 UTC, merged