PR semana-3
undefined-academy/semana-3 pull request #118
Opened 2023-04-11 18:06 UTC by angelmijarees

Semana-3
-Inicio de blog
-Cv con ejercicio Js
Formulario con Bootstrap

2023-04-18 04:55 UTC, OrcaCl requested changes
Pequeñas modificaciones necesarias, pero todo lo demás, impecable!

2023-04-18 04:55 UTC, OrcaCl commented on student-blogs/Angel-Mijares-3276/index.html
> +<html lang="en">
Sugerencia: Si el contenido de la página es en español, te recomiendo cambiar a lang="es"

2023-04-18 04:55 UTC, OrcaCl commented on student-blogs/Angel-Mijares-3276/index.html
> +    <link rel="stylesheet" href="style.css">
Recuerda usar rutas de archivos absolutas: href="/style.css"

2023-04-18 04:55 UTC, OrcaCl commented on student-cvs/Angel-Mijares-3276/main.mjs
> +function handleSumit(event) {
Acá no es un error terrible pero si es de idioma. debería ser handleSubmit(event).  Submit es el evento de enviar formulario. Lo mismo en la función, debes ejecutar handleSu**b**mit.

2023-04-18 15:15 UTC, angelmijarees commented on student-cvs/Angel-Mijares-3276/main.mjs
> +function handleSumit(event) {
Corregido

2023-04-19 17:36 UTC, Pancratzia commented on student-cvs/Angel-Mijares-3276/index.html
> +        <p><a href="contact.html" target="_blank">Form</a></p>
Deberías cambiar contact.html por form.html

2023-04-19 17:40 UTC, Pancratzia requested changes
En cuanto al **blog** me ha gustado mucho y veo que cumple con todo lo solicitado en la práctica.

En cuanto al **cv**, solo debes arreglar una ruta, pero o quitarla, pues veo que no has agregado estilos como tal al formulario, lo cual no era necesario para esta asignación. En cuanto al tamaño, se ve ideal en todos los dispositivos.

En cuanto al **formulario** veo que haz utilizado bootstrap y sus clases, pero te recomiendo encerrar todo en un contenedor, así no pasa lo de la siguiente imagen, donde el contenido llega hasta el borde: 

![image](https://user-images.githubusercontent.com/54899954/233156230-be3d7868-edc2-4766-924e-99f12c0cb917.png)

2023-04-19 17:42 UTC, OrcaCl approved these changes
Muy buenos avances.

2023-04-19 23:20 UTC, Pancratzia commented on student-forms/Angel-Mijares-3276/src/index.html
> +    class="container min-vh-100 d-flex justify-content-center align-items-center">
Agrega el siguiente cambio `class="container min-vh-100 d-flex justify-content-center align-items-center flex-column"` y estaría todo listo. Debes realizarlo porque al usar Flex y otorgar un min-width todos los objetos se van hacia el eje x. En este caso, si usas flex column los elementos van en dirección al eje y y no debes precoparte por ello

2023-04-20 02:21 UTC, angelmijarees commented on student-forms/Angel-Mijares-3276/src/index.html
> +    class="container min-vh-100 d-flex justify-content-center align-items-center">
Listo, muchas gracias

2023-04-20 02:30 UTC, Pancratzia approved these changes

2023-04-20 02:36 UTC, OrcaCl approved these changes

2023-04-29 23:25 UTC, merged