Blog Completed
undefined-academy/semana-3 pull request #14
Opened 2023-03-24 02:22 UTC by nanpipe

I have completed the blog full responsive with CSS Flex

2023-05-02 22:21 UTC, EzequielCaste requested changes
Aquí hay algo mal....
has subido la carpeta node_modules y eso no es correcto.
Deberías verificar que tu proyecto tenga el archivo .gitignore y que incluya a node_modules
![image](https://user-images.githubusercontent.com/51804994/235798184-698d7d8b-b1ac-479e-a4c4-e12cd74622af.png)
Aquí debería sólo modificar 12 archivos.

2023-05-04 14:02 UTC, EzequielCaste requested changes
Bueno vamos por partes,

> Subir la maquetación de la portada de blog usando Flexbox y CSS Grid a la carpeta
students-blog .

- Esto está bien. Aunque no pide que sea responsive, es bueno ir practicando lo de mobile first.
- En pantallas mobile se ve bien, cuando cambio a pantalla tablet 700px la tarjeta se extiendo muy a lo ancho, al igual que el texto. En estos casos es recomendable establecer un `max-width` a la Card para limitar el tamaño y evitar que se extienda. Con un `max-width` de 530px estarías bien. 
- Sino, la otra opción es cambiar el `breakpoint` cuando se transforma en 2 columnas y colocarlos antes o alrededor de 500px (menos de 500 1 columna, más de 500 2 Columnas)
- En Desktop se ve bien, sólo una sugerencia, tratar de limitar el width del contenedor, agregando un `max-width: 80%` y `margin: 0 auto` al `article`, para que no quede todo amontonado. Te muestro un ejemplo: 
![image](https://user-images.githubusercontent.com/51804994/236220654-f1cdf80d-474d-4e2f-9d82-9ce9348a2021.png)


> Subir la maquetación mobile first responsive de la hoja de vida a la carpeta students-
cv .

- En la hoja de vida (CV) no se están cargando los estilos. Veo que usaste archivos scss, eso no fue pedido en la clase. Puedes seguir usando archivos CSS.
- Tampoco pude ejecutar `npm run vite` porque no has incluido los scripts en el archivo `package.json`. Eso se logro iniciando el proyecto con `npm init -y` (debe ser por eso que no puedo ver lo estilos)

> Elegir entre Bootstrap o TailwindCSS y maquetar el formulario de contacto con dicha
tecnología en la carpeta student-forms .

- Tienes que revisar el `breakpoint 480px` porque la imagen de fondo se mueve y queda un espacio en blanco abajo de todo.
![image](https://user-images.githubusercontent.com/51804994/236229632-673d91eb-195c-42aa-9e7d-6e3f5ebaa124.png)
- Falta prevenir la acción por defecto del Formulario, sino al hacer "Enviar" se recarga la página.

Hay mucho por hacer, pero no te desanimes! Cualquier duda lo charlamos en Discord.
Saludos

2023-05-08 04:26 UTC, nanpipe commented
@EzequielCaste Cambios realizados, mejoras segun tus comentarios realizados. Muchisimas gracias por tu dedicación.

2023-05-09 13:17 UTC, EzequielCaste requested changes
Vamos bien!! :rocket: 
Algunos comentarios te dejé.

Ya casi está listo!

2023-05-09 13:17 UTC, EzequielCaste commented on student-cvs/IngFelipeSolarte-3451/css/style.scss
> +    color: v.$color-third;
![image](https://github.com/undefined-academy/semana-3/assets/51804994/52ad2b6b-364a-4574-8b49-2e5bee4fba0e)

Te recomiendo cambiar de color de texto, ya que no hace buen contraste con el fondo blanco.
Chrome y Firefox tienen una herramienta en DevTools (F12) que nos ayuda a ver si un color tiene el contraste adecuado. 

Contraste correcto: #333333 (para darte un ejemplo)  
![image](https://github.com/undefined-academy/semana-3/assets/51804994/b9aafacc-70e1-4059-8ee3-7a8a61e8beb7)

2023-05-09 13:17 UTC, EzequielCaste commented on student-forms/IngFelipeSolarte-3451/src/index.html
el Formulario no está mal, sólo que veo que hay **muchos** breakpoints o media queries, innecesario para algo tan simple como un formulario. Con un breakpoint estarías bien, 768px puede ser. En estos casos cuando se complica el tema de los breakpoints, lo mejor es comenzar desde la pantalla más pequeña (mobile: 320px a 500px) e ir trabajando hacia las pantallas más grandes.

2023-06-03 02:35 UTC, closed without merging