Ejercicioos semana 3
undefined-academy/semana-3 pull request #142
Opened 2023-04-16 21:38 UTC by fedegomezc

Los ejercicios según los commit son:

- **Ejercicio Clase 1 - blog**
- **desktop styles and add icons**  - último comit del ejercicio clase 2 (Mobile First Responsive de su hoja de vida)
- **Ejercicio clase 3**  
- **ejercicio 4 formulario con Bootstrap**

Por último traje los cambios del repositorio **undefined-academy/semana-3** y luego hice PR.

2023-04-25 00:41 UTC, Danlarte commented
Hola Fede, vi tu repo y los ejercicios cumplen con lo requerido. Buen trabajo!
PD: podrías pasar por mi repo, necesito feedback de la semana 3, muchas gracias.

2023-04-25 01:12 UTC, fedegomezc commented
> Hola Fede, vi tu repo y los ejercicios cumplen con lo requerido. Buen trabajo! PD: podrías pasar por mi repo, necesito feedback de la semana 3, muchas gracias.

Hola @Danlarte , gracias! 
Te aviso q me hiciste un comentario y no una review. Me podrías poner la review?
Para tener tu **_approve_** tenes que ir la solapa de `Files changed` y allí en el botón verde que dice `review changes`. Pones tu comentario ahí, seleccionas `Approve` y luego `Submit review`.
Cualquier duda escribime por discord a Fede.GC#5692
Dale, yo te doy feedback de tu repo. Saludos!

2023-04-25 23:22 UTC, Danlarte approved these changes
Todos los ejercicios cumplen con las tareas solicitadas.

2023-04-26 02:59 UTC, fedegomezc commented
> Listo Fede, ya hice la review, saludos.

Muchas gracias!

2023-05-03 21:35 UTC, camilasilvab requested changes
Al revisar tus archivos en la carpeta form hiciste el formulario con el preprocesador SASS pero dentro de los requisitos de el PR de la semana 3 se pide que el formilario se haga con Bootstrap o TailwindCSS

2023-05-03 22:02 UTC, camilasilvab commented
Cambio mi comentario, ya me hiciste dar cuenta que lo hiciste con Bootstrap, por lo demás un buen trabajo

2023-05-03 22:02 UTC, camilasilvab approved these changes

2023-05-03 22:14 UTC, merged