Ejercicios de la Semana 3
undefined-academy/semana-3 pull request #146
Opened 2023-04-18 01:19 UTC by Gaston095

# Resolución ejercicios de la semana 3.

1- Hice un ***fork*** del repositorio de la semana-3 https://github.com/undefined-academy/semana-3.
2- Clone el repo ***fork*** en mi home.
3- Subí la maqueta del blog utilizando ***flex-box*** y ***grid*** a la carpeta ***Gaston095_2770/students-blog*** del proyecto.
4- Subí la maqueta ***mobile firt*** de mi hoja de vida a la carpeta ***Gaston095_2770/students-cv***.
5- Instale ***Boostrap + Vite*** , y realice la maqueta del formulario de contacto.

2023-04-19 17:11 UTC, Pancratzia commented on student-blogs/Gaston095_2770/style.css
> +}
Como sugerencia, podrías colocar un width del 100%, así logras que tus imagenes sean responsive y se adapten a su contenedor. Sin embargo, si quieres que tengan ese ancho deberías centrarlas. En este momento están alineadas a la derecha

2023-04-19 17:15 UTC, Pancratzia requested changes
Hola! En cuanto a tu **blog**, veo que utilizaste bien tanto el flex como el grid. Tienes un pequeño detalle en las imágenes pero en sí no es algo que tenga que ver con la asignación como tal, sino un detalle estético. 

Para la parte del **CV** veo que te falta la parte del JS de la semana 3 y utilizar vite. Sin embargo, viendo el diseño lo único que puedo acotar es que tal vez el formulario debería usar todo el ancho de la página cuando esté por encima de los 768px. Es decir, en desktop

2023-04-26 10:52 UTC, Gaston095 commented on student-blogs/Gaston095_2770/style.css
> +}
Hola Muchas gracias por tu revisión. le coloque un width del 100% pero no entiendo a que te refieres con que estan alineadas a la derecha. Ya que la imagen se esta mostrando completa.

2023-05-03 15:26 UTC, fedegomezc commented on student-blogs/Gaston095_2770/style.css
> +}
Hola Gastón. Estaba revisando tu PR y me puse a leer las observaciones. Lo que se refiere es que al abrir la página en una pantalla más grande las imágenes no quedan centradas.
 Acá hice captura.
![image](https://user-images.githubusercontent.com/106751267/235962326-bad4bbb5-4052-4efc-bb98-068e7ca24947.png)

Para centrarlas se me ocurre que a la etiqueta padre ( .card) ponerle `display: grid` y a la etiqueta `img `ponerle `align-self: center`

2023-05-03 16:04 UTC, fedegomezc requested changes
Hola, en cuanto al CV falta el ejercicio de la clase 3. Como mencionó @Pancratzia la idea es usar vite como indica la consigna y agregar el archivo main.mjs para prevenir el comportamiento por defecto del envío de la información al servidor del formulario.
Y una opinión, en el CV el formulario cuando el media queries para desktop creo que quedaría mejor centrado o que ocupe todo el ancho.

2023-05-03 18:39 UTC, Gaston095 commented on student-blogs/Gaston095_2770/style.css
> +}
no podia ver eso ya que desde la notebook se ve bien centrado! te gradesco mucho por las capturas, ya voy a arreglarlo

2023-05-03 21:20 UTC, fedegomezc commented on student-cvs/Gaston095_2770/index.html
> +    <script type="module" src="/main.mjs"></script>
Esto es solo una recomendación. Tengo entendido que el script, por cuestiones de rendimiento, es mejor colocarlo dentro del <head> y se le agrega async defer.
<script **async defer** type="module" src="/main.mjs"></script>

2023-05-03 21:21 UTC, fedegomezc approved these changes
Considero que cumple con lo solicitado. Éxitos!

2023-05-04 18:51 UTC, camilasilvab approved these changes
Buen trabajo

2023-05-04 19:37 UTC, merged