Semana-3
undefined-academy/semana-3 pull request #150
Opened 2023-04-20 00:51 UTC by EdwinOrtizCantillo

## Semana 3

- Ejercicio Clase 1 - blog
- Ejercicio clase 2 (Mobile First Responsive de su hoja de vida)
- Ejercicio clase 3 formulario con Bootstrap
- Por último traje los cambios del repositorio undefined-academy/semana-3 
- Luego el PR

2023-04-20 01:07 UTC, dfm555 requested changes
Debes crear un .gitignore y eliminar la carpeta node_modules

2023-04-20 01:47 UTC, EdwinOrtizCantillo commented
Gracias hermano lo intente y creo que ya lo hice

2023-04-20 01:59 UTC, dfm555 requested changes
Elimina todos los archivos de este tipo .png:Zone.Identifier

2023-04-20 11:56 UTC, EdwinOrtizCantillo commented
gracias hermano ya lo hice, aun no entiendo porque no me funciono el .gitignore

2023-04-20 13:20 UTC, dfm555 requested changes
En los últimos commits moviste el .gitignore  y ahora debes resolver los conflictos

2023-04-25 22:50 UTC, EdwinOrtizCantillo commented
hola dfm555 me revisas nuevamente por fa

2023-04-26 13:06 UTC, dfm555 requested changes
@EdwinOrtizCantillo siguen los conflictos

Para resolverlos trata de hacer esto.

/.gitignore no puede ser eliminado 
/student-forms/.gitignore no debe estar allí mueve su contenido al /.gitignore

2023-04-26 15:19 UTC, dfm555 requested changes

2023-04-26 15:19 UTC, dfm555 commented on .gitignore
@EdwinOrtizCantillo este archivo no lo puedes eliminar por eso sigues teniendo conflictos

2023-04-26 15:27 UTC, dfm555 approved these changes

2023-04-27 00:25 UTC, EdwinOrtizCantillo commented
> En rasgos generales, está MUY bien. Tendría pequeñas observaciones, como...
> 
> 1. **Formulario** , el textarea de la "Descripción del proyecto", el "placeholder" no se desaparece cuando se escribe.
> 2. **CV** , está perfecto. Es verdad que se ve un poco extraño en resoluciones de móviles<500px
> 3. **Blog** , perfecto. Algo super mínimo, es que el tanto el logo, como el fondo que está encima de la barra de navegación, se mueve un poco, y el fondo del logo se encoge un montón cuando aplico el modo responsivo.
> 
> Son observaciones que poco tienen que ver con los ejercicios, si no más por cuestión de "gustos", **¡muy bien! **💪🏽

2023-04-27 00:25 UTC, closed without merging

2023-04-27 12:53 UTC, dfm555 commented
@EdwinOrtizCantillo por qué cerraste tu pull request ?

2023-04-27 12:59 UTC, EdwinOrtizCantillo commented
> @EdwinOrtizCantillo por qué cerraste tu pull request ?

Hermano que pena fue un accidente