Creacion de pull request de la semana 3.
undefined-academy/semana-3 pull request #153
Opened 2023-04-21 14:45 UTC by blonardi

1- Añadi los archivos de mi CV a la carpeta student-cvs.
2- Añadi archivos de mi formulario hecho con tailwind.
3- Añado archivos del blog hecho con css.

2023-04-21 19:15 UTC, MauBedoya requested changes
Esta bueno el trabajo, pero habría que revisar el tema del "mobile first" y "desktop first"

2023-04-21 19:15 UTC, MauBedoya commented on student-cvs/bautista-lonardi-9435/style.css
> +@media screen and (max-width: 992px) {
para ser "mobile first" lo que se usa es el `min-width` ya que se indica que "cuando la pantalla tenga este mínimo de ancho aplica los estilos para desktop", al usar `max-width` estaríamos dándole un enfoque "desktop first"

2023-04-26 17:58 UTC, blonardi commented on student-cvs/bautista-lonardi-9435/style.css
> +@media screen and (max-width: 992px) {
Perfecto Mau, ahi arregle la parte de mobile first y media queries al blog. Me falta la parte de mobile first en el CV.

2023-04-26 21:26 UTC, MauBedoya commented on student-cvs/bautista-lonardi-9435/style.css
> +@media screen and (max-width: 992px) {
genial entonces 👍, el CV lo puedes ir trabajando tranquilamente en semana 4 para las tareas de Sass

2023-04-26 21:27 UTC, MauBedoya approved these changes

2023-05-13 02:13 UTC, closed without merging