PR Semana 3, Ejercicios 1,2,3 y 4 en Bootstrap.
undefined-academy/semana-3 pull request #168
Opened 2023-04-28 05:21 UTC by OrcaCl

Solicitud de PR de ejercicios de semana-3.

El ejercicio final de Bootstrap puede que tenga errores o que haya hecho las cosas de otra forma, por lo que agradecería el feedback para poder hacerlo mejor.

:)

Por fin a semana 4.

2023-05-02 12:08 UTC, Lmendev requested changes
Hola! Me gustó mucho el estilo del form que es como dark y no me quemó lo ojos revisando jajaj 👍 

El único cambio que le haría es en los `href` de `href="/archivo.ejemplo"` a `href="./archivo.ejemplo"` con un punto para que los imports sean relativos al archivo actual.

Estuve tratando de verlo con un live server y la ruta del css al ser 
```html
<link rel="stylesheet" href="/styles.css">
``` 

resolvía como `http://127.0.0.1:5500/styles.css` en vez de `http://127.0.0.1:5500/student-blogs/Caffa-4633/styles.css` por lo que no cargaba los estilos al no existir ese archivo

Añadiéndole el `.` en la ruta esto se soluciona

2023-05-03 03:24 UTC, OrcaCl commented
> Hola! Me gustó mucho el estilo del form que es como dark y no me quemó lo ojos revisando jajaj 👍
> 
> El único cambio que le haría es en los `href` de `href="/archivo.ejemplo"` a `href="./archivo.ejemplo"` con un punto para que los imports sean relativos al archivo actual.
> 
> Estuve tratando de verlo con un live server y la ruta del css al ser
> 
> ```
> <link rel="stylesheet" href="/styles.css">
> ```
> 
> resolvía como `http://127.0.0.1:5500/styles.css` en vez de `http://127.0.0.1:5500/student-blogs/Caffa-4633/styles.css` por lo que no cargaba los estilos al no existir ese archivo
> 
> Añadiéndole el `.` en la ruta esto se soluciona

Hola, 

Muchas gracias por revisar.
Ya estoy por subir el fix.

Atte.

2023-05-03 17:50 UTC, StephanyCS1 commented on student-blogs/Caffa-4633/index.html
# Hola

En el blog, en la vista mobil queda todo el contenido en la misma vista y no seria muy visible
![image](https://user-images.githubusercontent.com/108440139/235988268-5ba86757-b0af-4205-8352-19f74f3aa3a0.png)
seria bueno ajustarla.

2023-05-03 17:50 UTC, StephanyCS1 commented on student-cvs/Caffa-4633/index.html
# CVS
el diseño esta chevere, como recomendación en la vista de mobile le puedes quitar un poquito de padding y asi el diseño se ajusta mejor

# El from
En la vista mobile quedaría complicado usarla, ya que queda muy pequeña para manipularla
![image](https://user-images.githubusercontent.com/108440139/235991696-c7b3d7a8-5578-419d-a62b-249e7baff51c.png)

2023-05-06 06:51 UTC, OrcaCl commented on student-blogs/Caffa-4633/index.html
Honestamente no le di mucho pensamiento al tema mobile pero voy a hacer los ajustes. No saco nada con seguir los capítulos si dejo tareas incompletas.

Gracias por el input

2023-05-22 01:20 UTC, OrcaCl commented on student-blogs/Caffa-4633/index.html
Hola, 
Ayer pude hacer los ajustes a Mobile. Podrías revisar nuevamente para saber si está ok??

Muchas gracias.

2023-05-22 11:27 UTC, Lmendev approved these changes
🚀

2023-05-23 17:01 UTC, StephanyCS1 approved these changes

2023-05-27 16:55 UTC, merged