My personal Blog
undefined-academy/semana-3 pull request #172
Opened 2023-05-03 03:30 UTC by Oziel07

# My personal blog.
## Usando FLEX & GRID.

- Usando una imagen en Header.
- Body se utilizan <div> clase *container*.
- Tambien se utiliza <div> clase *article*.
- Se maneja en CSS display flex y Grid.

2023-05-03 03:52 UTC, Oziel07 commented
# CV with mobile first.

- Utilizando Flex CSS, primero se diseño version Mobile para pasar a la version de escritorio.

2023-05-03 04:18 UTC, Oziel07 commented
# Ejercicio Semana 3.
## Formulario con bootstrap.
- Se realiza el formulario utilizando bootstrap.
- Tambien se agrega test console "Hola mundo"

2023-05-04 19:21 UTC, JoeOsG requested changes
Puedes quitar el vite config.
Eso es para tu local.

2023-05-04 19:42 UTC, JoeOsG approved these changes
### Bien

2023-05-04 19:43 UTC, Oziel07 commented
> Puedes quitar el vite config. Eso es para tu local.

Buena sugerencia, gracias

2023-05-15 05:03 UTC, MrRedu approved these changes
### ¡Bien ahí!
La verdad hay algunas cosas mejorables, pero son bastantes mínimas, nada para alarmarse. No perjudican al funcionamiento de la página. Te daré approved, aunque sinceramente me gustaría mucho que -acomodaras- algunas de las cosas que comenté antes de enviarlo al canal de #pr-listo-para-merged, ¿vale?

Buen trabajo, me gustó mucho el estilo de tu blog ⚔️

2023-05-16 03:45 UTC, Oziel07 commented on student-blogs/Oziel-3111/index.html
> +    <header>¡Bienvenido a mi blog!</header>
Arreglado! Gracias.

2023-05-16 04:11 UTC, Oziel07 commented
> ### ¡Bien ahí!
> 
> La verdad hay algunas cosas mejorables, pero son bastantes mínimas, nada para alarmarse. No perjudican al funcionamiento de la página. Te daré approved, aunque sinceramente me gustaría mucho que -acomodaras- algunas de las cosas que comenté antes de enviarlo al canal de #pr-listo-para-merged, ¿vale?
> 
> Buen trabajo, me gustó mucho el estilo de tu blog ⚔️

2023-05-16 04:12 UTC, Oziel07 commented on student-forms/Oziel-3111/package.json
> +  "scripts": {
Hice los cambios que me solicitaste pero no he podido hacer un pull nuevo, ando revisando.

2023-05-16 04:45 UTC, Oziel07 commented
## Se agregan cambios solicitados.

2023-05-16 04:46 UTC, Oziel07 commented on student-forms/Oziel-3111/package.json
> +  "scripts": {
Ya quedaron los cambios, gracias por tus comentarios.

2023-05-16 16:09 UTC, merged