Semana 3 PR
undefined-academy/semana-3 pull request #174
Opened 2023-05-03 04:05 UTC by jorge9372

# Procedimiento 

# Primera parte
✔️Hacer fork en el repositorio que se nos fue indicado: ``` https://github.com/undefined-academy/semana-2 ```.
✔️Clonar el repositorio para acceder de forma local ```git clone <enlace o llave proporcionado en nuestro GitHub> ```.
✔️[EJERCICIO]Crear su propio layout de cards que muestre las entradas de su blog usando el layout visto en clase.
✔️[EJERCICIO]Crear una versión Mobile First Responsive de su hoja de vida (CV).
✔️[EJERCICIO]Elegir entre Bootstrap o TailwindCSS y maquetar el formulario de contacto con dicha tecnología, en este caso se utilizó Bootstrap.
✔️Realizar commit paso por paso a medida que se culmina cada ejercicio: ```git commit -m ""```  
✔️```git push origin main``` luego de haber realizado uno a uno los commit.

Se debe cumplir con la siguiente estructura para el PR:
``` 
.
├── student-cvs/
│ └── JorgeVillafraz-6924/
│     ├── index.html
│     ├── form.html
│     ├── styles.css
│     └── main.mjs
├── student-blogs/
│ └── JorgeVillafraz-6924/
│     ├── index.html
│     └── styles.css
└── student-forms/
    └── JorgeVillafraz-6924/
       └── Bootstrap/
            ├── src
            └── package.json
 ```

Finalmente se elabora el respectivo pull request correspondiente a la semana 3

2023-05-03 04:54 UTC, MrRedu requested changes
Observaciones:

### Blog:
- Se siente un poco raro que el blog, aunque use GRID no tenga modo responsive. La verdad desconozco, porque siendo sincero no recuerdo si realmente es necesario que sea responsive para esta semana, pero definitivamente luego tendrá que serlo. Así que, podrías ir echándole responsive-design.

### CV:
- Fino todo. No puedo ver ninguna mejora.

### Formulario:
- Me gustó el botón que aparece en el modo celular.
- Te recomiendo que no hagas el formulario tan ancho, igual con la página de blog. Hacerlas un poco menos ancha, para no tener que voltear la cabeza. Eso tiene una razón, Guille lo explica en alguna de las clases
- Bien con los required en cada campo del formulario

2023-05-03 04:54 UTC, MrRedu commented on student-blogs/JorgeVillafraz-6924/index.html
> +    <link>
🤔

2023-05-03 04:54 UTC, MrRedu commented on student-blogs/JorgeVillafraz-6924/index.html
> +        </nav>
Yo pensaría, que te sale mejor hacer el nav-bar, fuera del grid.

2023-05-03 04:54 UTC, MrRedu commented on student-forms/JorgeVillafraz-6924/bootstrap/src/js/main.js
> +}
Acá, te faltaría un `console.log("mensaje")`, para saber si está funcionando lo de prevenir el comportamiento por default.

2023-05-03 04:54 UTC, MrRedu commented on student-forms/JorgeVillafraz-6924/bootstrap/package.json
> +  "main": "index.js",
Agregar ` "module": "module",`, antes de scripts

2023-05-03 05:00 UTC, MrRedu commented
Las cosas que hice para poder correr el proyecto, fueron:

- Agregar el `"module": "module",` al `package.json`
- Dividí los archivos de js de esta manera:
![image](https://user-images.githubusercontent.com/73679190/235835510-647654df-62a7-4f3c-a9ca-f2301d9fa7cf.png)
- Moví los scripts al final de la página del HTML, pero tengo mi duda si es necesario. Si te funciona arriba, déjalo ahí no más
![image](https://user-images.githubusercontent.com/73679190/235835618-5cf0af5c-a7f9-4e93-9c04-d9a54bc2deb8.png)

2023-05-04 23:15 UTC, jorge9372 commented on student-blogs/JorgeVillafraz-6924/index.html
> +    <link>
Listo por aca

2023-05-04 23:15 UTC, jorge9372 commented on student-forms/JorgeVillafraz-6924/bootstrap/src/js/main.js
> +}
lsito

2023-05-04 23:15 UTC, jorge9372 commented on student-forms/JorgeVillafraz-6924/bootstrap/package.json
> +  "main": "index.js",
listo

2023-05-04 23:16 UTC, jorge9372 commented on student-blogs/JorgeVillafraz-6924/index.html
> +        </nav>
listo lo modifique

2023-05-04 23:17 UTC, jorge9372 commented
@MrRedu Listo lo que me comentaste revisa por favor en lo que puedas.

Quedo atento.

2023-05-04 23:37 UTC, MrRedu approved these changes
### Muy buen trabajo! 💪🏼

2023-05-04 23:41 UTC, EzequielCaste approved these changes

2023-05-05 12:59 UTC, merged