Ejercicios de semana 3
undefined-academy/semana-3 pull request #19
Opened 2023-03-25 06:11 UTC by JoseCamilo84

Para el formulario de contacto elegí Bootstrap
El blog apliqué el grid y flex
y para la maquetación usé la media-query para dispositivos mobile

2023-03-25 18:14 UTC, jaardila-3 approved these changes
Muy buen trabajo, cumple con todos los ejercicios, recuerda consultar defer y async en las etiquetas script, ellas se descargan en paralelo y no bloquean el cargue del DOM

2023-03-26 05:29 UTC, JoseCamilo84 commented
ah ok listo... lo consultaré, gracias

2023-03-29 18:20 UTC, pablo-alex requested changes
Hola @JoseCamilo84 veo que todo esta correcto la pagina CV es responsive y en el blog se esta utilizando atributos flex and grid. Si le puedes agregar tambien al ultimo formulario para evitar la recarga de la pagina seria todo.

2023-03-29 22:08 UTC, JoseCamilo84 commented on student-forms/Jose-Camilo-8399/bootstrap/src/js/main.js
> +import * as bootstrap from 'bootstrap';
Me ayudas con tu aprobación, gracias

2023-03-29 23:37 UTC, pablo-alex approved these changes

2023-03-30 00:42 UTC, merged