PR Semana 3 - Blog/mobile-first/Bootstrap
undefined-academy/semana-3 pull request #198
Opened 2023-06-14 21:58 UTC by Alvarordev

Buenas, subo mi pull request para esta semana 3

## Pasos seguidos

### Blog

* Cree un blog con grid y flex
* lo subí en la carpeta student-blogs
* hice un push en mi fork de la semana 3

### Responsive

* Volví a hacer mi cv con mobile-first
* Agregue vite como dependencia y un main.js
* lo subí en la carpeta student-cvs
* hice un push en mi fork de la semana 3

### Bootstrap y Tailwind

* Volví a hacer mi formulario con bootstrap
* lo subí en la carpeta student-forms
* hice un push en mi fork de la semana 3

2023-06-18 16:32 UTC, Lunisa202 commented on student-blogs/hazard-2472/index.html
> +                <img src="image.webp" alt="">
Hola, quizás yo le agregaría alguna descripción al atributo alt en las imágenes, por temas de accesibilidad, por todo lo demás que he revisado, está muy bueno tu blog!

2023-06-18 16:52 UTC, Lunisa202 requested changes

2023-06-18 16:52 UTC, Lunisa202 commented on student-cvs/hazard-2472/styles.css
> +    .description {
Creo q si cumple con ser responsive! Me gustó mucho tu diseño y los colores usados 🤗

2023-06-18 16:52 UTC, Lunisa202 commented on student-forms/hazard-2472/src/index.html
> +                        <option value="design">Diseño web</option>
Creo que has usado muy bien las clases predefinidas de Bootstrap, el formulario se ve bien también en pantallas pequeñas.

2023-06-19 00:45 UTC, Alvarordev commented on student-blogs/hazard-2472/index.html
> +                <img src="image.webp" alt="">
Hola!, gracias por la sugerencia. Ya agregué una descripción para los atributos alt.

2023-06-20 13:58 UTC, Lunisa202 approved these changes
Todo excelente!

2023-07-07 02:46 UTC, closed without merging