Semana 3-PR (2)
undefined-academy/semana-3 pull request #199
Opened 2023-06-14 23:24 UTC by Lunisa202

# Mi PR de la semana 3
1. Mi Blog:  He creado un blog con la temática de crianza de perros, usé grid en la barra de navegación (flex dentro de algunos ítems) y grid en la sección de las cards de los artículos. En las cards y su contenido he usado flexbox. Hice algunos efectos de agrandamiento de la letra cuando hubiera un hover en los artículos.
2. Mi CV: He creado mi página del CV, el cual incluye su form de contacto. Todos sus elementos en responsive, por ahora solo he considerado una media query.
3. Form con Bootstrap: he creado un formulario con las clases de bootstrap, el cual también es responsive, contiene package.json de configuración y con "vite" como dependencia de desarrollo.

2023-06-18 19:04 UTC, StephanyCS1 requested changes
El diseño web esta chevere, te recomiendo ajustar un poco el input del buscador ya que queda pegado a la parte derecha de la ventana
Para la parte de mobile, no se te esta ajustando el diseño al tamaño de la pantalla

2023-06-18 19:19 UTC, StephanyCS1 approved these changes
El diseño esta chevere, le podrías agregar un Scroll-behavior para que al ir a las otras secciones desde el menú el cambio sea menos rápido 
- En el diseño del form si tienes el menú hamburguesa pero en el cv se quedan todas las opciones en la barra

2023-06-19 01:02 UTC, Alvarordev commented
Me gusta mucho tu blog, se ve una buena aplicación del grid y flex, una cosa que cambiaria es que el input de busqueda no este pegado a la derecha de la pantalla sino un poco más al centro.

2023-06-19 16:06 UTC, nencodev approved these changes
¡Está chévere!

2023-06-20 16:37 UTC, Alvarordev approved these changes
Se ve todo bien 👍🏻

2023-06-20 20:56 UTC, StephanyCS1 approved these changes

2023-06-20 23:23 UTC, merged