Blog-flexbox-grid
undefined-academy/semana-3 pull request #21
Opened 2023-03-25 14:17 UTC by Alexisdc5

2023-04-12 22:58 UTC, Lmendev requested changes
Dejé un comentario!

2023-04-12 22:58 UTC, Lmendev commented on .gitignore
> +*:Zone.Identifier
Este archivo no debería haberse modificado

2023-04-13 03:00 UTC, Vene15 approved these changes

2023-04-13 03:01 UTC, Vene15 commented
Lo veo muy bien!!  😀

2023-04-13 03:23 UTC, Alexisdc5 commented on .gitignore
> +*:Zone.Identifier
Hola Lmendev,, el archivo fue modificado por que presentaba conflictos en la rama y fue la solución q me dio unos de los mentores.
Gracias por tu comentario

2023-04-13 11:53 UTC, MauBedoya approved these changes
El objetivo de hacer el blog y conseguir la version mobile first se cumple, igual te recomendaría que revises los detalles que te comente para tu siguiente PR o si puedes incluso para actualizar este.

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/index.html
> +            <a href="https://github.dcom/Alexisdc5">Mi perfil de github</a>
hay un error en el link: ".dcom"

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/main.css
> +  height: 20px;
mmm este `height` en el body parece estar demás, además en la version móvil el margen funcionara mejor dando un espacio entre el link de tu github y la parte inferior de la pantalla

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/main.css
> +* {
aquí parece que tratas de hacer un reset de algunas propiedades, creo que faltaría que apliques el:
```css
margin: 0;
```

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/main.css
> +  margin: 20px;
normalmente la propiedad que se suele usar para dar un "espaciado" alrededor de los elementos es el **padding** (el margin es mas usado para centrar elementos con el **auto**), si aplicas el reset que te recomiendo en el comentario de arriba y cambias de `margin` a `padding` no debería haber problema al aplicar esto.

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/main.css
> +  }
también ten en cuenta que estas propiedades del body no son necesarias si ya las definiste antes (en el código mobile first), ya que no ocurre ningún cambio al pasar a la version de desktop (esto si aplicas lo recomendado sobre el `height` y el `padding` de los anteriores comentarios).

2023-04-13 11:53 UTC, MauBedoya commented on student-cvs/alexis87-6482/index.html
> +        <article class="presentacion">
esto es un poco más relacionado a el PR de semana 2, quizá la etiqueta correcta aquí es `main`, **article** se utiliza para englobar contenido que funcione independientemente del contexto de tu CV (algo así como cada artículo individual de tu blog), mientras que `main` se encargaría de decirle al navegador que su contenido es **el contenido principal de tu CV y relacionado entre si**

2023-04-15 19:29 UTC, merged