Semana 3 - Students cv,blog y form
undefined-academy/semana-3 pull request #23
Opened 2023-03-25 20:01 UTC by MariaSolArroyo

# SEMANA 3 🤓

Se realizó fork del repositorio de la **Semana 3**  y luego el pull request con lo siguiente:

- [ Maquetación de la portada de blog usando **Flexbox y CSS Grid** ] ✔️ - **📁 students-blog**

- [ Maquetación Mobile First responsive] ✔️ - **📁 students-cv**

- [ Maquetación del formulario contacto (en mi caso hice tambien de la página principal) usando **Bootstrap** ] ✔️ - **📁 students-forms**

2023-03-27 17:55 UTC, MauBedoya requested changes
Se ve bastante bien, solo que me aparece que existe un conflicto de ramas con tu trabajo, quizá tiene que ver con los `.gitkeep` que eliminaste o cambiaste, de todas formas te deje unos cuantos comentarios más que nada de detallitos 👀

2023-03-27 17:55 UTC, MauBedoya commented on student-cvs/MariaSolArroyo-9830/css/main.css
> +    width: 50%;
este `width: 50%` parece que se podría eliminar y mejoraría un poco el comportamiento del ancho de los botones contenidos, en dispositivos angostos se deforman los botones:
![image](https://user-images.githubusercontent.com/111880575/228018499-ff45a985-f427-4d1a-9557-c18f0ab5da6d.png)

y en desktop se aumenta la altura de los botones para cumplir el 50% y se ve el contenido de los botones sin centrar, o quizá esto último está pensado como parte del diseño? 🤔
![image](https://user-images.githubusercontent.com/111880575/228018826-74707213-f599-4444-94e7-2116ae090ccb.png)

2023-03-27 17:55 UTC, MauBedoya commented on student-cvs/MariaSolArroyo-9830/index.html
> +        <thead>
esto ya es un poco a gustos, en la version mobile tal vez ponerle un `border` a las casillas de la tabla harían un poquito más claro que comandos (`td` con `strong`) están relacionados a que contenidos, en desktop creo que se ve bien.

2023-03-27 17:55 UTC, MauBedoya commented on student-cvs/MariaSolArroyo-9830/html/contacto.html
> +                  <label for="emailcontacto">Email</label>
puede ser buena idea hacer un `flex-firection: column` en esta parte de `whatsapp` y `Email` en la version mobile

2023-03-27 17:55 UTC, MauBedoya commented on student-forms/MariaSolArroyo-9830/src/html/contacto.html
> +        <form>
aquí como comentario quizá podría limitarse un poco el ancho del `main` para que el formulario no ocupe casi toda la pantalla en desktop 👀

2023-03-28 04:23 UTC, MariaSolArroyo commented on student-forms/MariaSolArroyo-9830/src/html/contacto.html
> +        <form>
Gracias ppor tu feedback ya acomode todo lo que me comentaste solo me falta esto que lo revisaré estos días con mas tiempo!muchisimas gracias

2023-03-28 04:25 UTC, MariaSolArroyo commented on student-forms/MariaSolArroyo-9830/src/html/contacto.html
> +        <form>
de paso te pregunto como haces para poder ver la pagina?porque he revisado trabajos y solo he visto codigo por codigo como haces la vista previa?

2023-03-28 12:04 UTC, MauBedoya commented on student-forms/MariaSolArroyo-9830/src/html/contacto.html
> +        <form>
En el caso de los CV's solo copio el código a unos archivos html, css y js que tengo separados para revisiones y utilizo la extension `Live Server` para ver la página en el navegador, también se puede usar `Vite` como Guillermo, eso sí, las imágenes a fuerzas habría que descargarlas, pero por lo general la estructura no cambia si se ve sin las imágenes (por esto también sería bueno usar servicios como `Cloudinary` para subir nuestras imágenes y solo usar la URL en nuestros HTML).
Para bootstrap y tailwind casi lo mismo, tengo unas carpetas con las configuraciones que aprendimos en la clase de frameworks UI y solo basta copiar el contenido del HTML, si la configuración está bien hecha se deberían poder ver los estilos automáticamente. Espero que te sirva 👀
![image](https://user-images.githubusercontent.com/111880575/228229561-3710480d-0aa9-457c-bf84-d092d6dac344.png)

2023-03-28 12:11 UTC, MauBedoya reviewed
Se sigue mostrando el mensaje de conflicto de ramas 👀.
![image](https://user-images.githubusercontent.com/111880575/228231676-a2faf35f-085e-4685-bd9e-885f71473f26.png)

Puede ser por estos `.gitkeep` que parece que se borraron
![image](https://user-images.githubusercontent.com/111880575/228231475-cd4e6de6-f030-4d0a-af33-adfebbbf546d.png)

2023-03-29 00:32 UTC, truquinio approved these changes

2023-03-29 01:03 UTC, MauBedoya approved these changes

2023-03-30 09:06 UTC, merged