Semana 3 css
undefined-academy/semana-3 pull request #3
Opened 2023-03-22 15:25 UTC by marisolSv22

1. Realice las css grid y flexbox con lo aprendido en el bootcamp de js, html css y node js
2. Puse el codigo html de mi formulario y le agregue más estilos css y lo puse responsive mobile firts 
3. Cree el package .json, descargue como dependencia de desarrollo a vite  y añadí los estilos de tailwind css como paquete y segui los pasos para incluirlo en mi documento html, pero estos todavía no son responsive

2023-03-29 15:29 UTC, JoseCamilo84 requested changes

2023-03-29 15:29 UTC, JoseCamilo84 commented on student-cvs/MarisolSalazarV-6177/form.html
> +
Hola... no veo en la carpeta el archivo de cv? solo veo el form.html?
creo que te hace falta

2023-03-29 15:38 UTC, JoseCamilo84 requested changes

2023-03-29 15:38 UTC, JoseCamilo84 commented on student-cvs/styles.css
> +    font-size: 20px;;
Aqui tienes un punto y coma de más

2023-03-29 15:42 UTC, marisolSv22 commented on student-cvs/MarisolSalazarV-6177/form.html
> +
No entiendo tu comentario, en index.html esta mi info de la CV

2023-03-29 15:42 UTC, marisolSv22 commented on student-cvs/styles.css
> +    font-size: 20px;;
Gracias

2023-03-29 15:42 UTC, marisolSv22 commented on student-cvs/index.html
> +    <div class="footer">
Gracias por la ayuda de verdad que esto no lo sabia

2023-03-30 23:40 UTC, JoseCamilo84 approved these changes

2023-03-31 22:56 UTC, truquinio commented
Hola Marisol, cómo estás? Revisa tu rama que pareciera tener conflictos. A mi me pasó igual en otra PR y hasta que no los resolví, no me le dieron merge

2023-03-31 22:59 UTC, truquinio requested changes
Te dejé un comentario x tu rama

2023-04-03 15:04 UTC, marisolSv22 commented
> Hola Marisol, ¿cómo estás? Revisa tu rama que parece tener conflictos. A mi me pasó igual en otra PR y hasta que no los resolví, no me le dieron merge👇👇👇

Eso me la he pasado haciendo, corrigiendo conflictos y se me volvio a dañar

2023-04-03 15:34 UTC, truquinio approved these changes

2023-04-03 19:47 UTC, dfm555 requested changes

2023-04-03 19:47 UTC, dfm555 commented on student-forms/vite.config.js
Mueve este archivo dentro de tu carpeta Marisol/

2023-04-03 21:52 UTC, marisolSv22 commented
> No deberías crear el archivo .gitignore

Lo cree porque cuando hice el fork no estaba

2023-04-03 21:54 UTC, marisolSv22 commented on student-forms/vite.config.js
Listo ya la movi de lugar

2023-04-03 22:06 UTC, dfm555 commented
@marisolSv22 @cadifilippo revisé y el .gitignore es igual por eso hice el merge del PR

2023-04-03 22:06 UTC, merged