Ejercicios semana-3
undefined-academy/semana-3 pull request #4
Opened 2023-03-22 16:04 UTC by Andrssnsdc

2023-03-23 17:57 UTC, Alexis033 requested changes
Hola, veo todo lo que se pidió, hay algunos detalles que se pueden mejorar, pero lo veo bien

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/index.html
> +        <nav class="home"> <a class="git" href="https://github.com/Andrssnsdc"> Este es mi perfil de Github </a> </nav>
Hola, a links como este podrías agregarle un target blank para que se abran en otra pestaña y no te saquen de tu cv.

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/index.html
> +        <nav>
Hola, normalmente la etiqueta nav se usa dentro de un header cuando va en la parte superior de la pagina.

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/index.html
> +<body> <section>
Este section aquí es raro, podrías revisar si realmente es necesario o es mejor un quitarlo.

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/index.html
> +    <h3>Sobre mi:</h3>
Este article y el siguiente deberían ser solo uno, mira que el h3 es el título de lo que hablas en el siguiente artículo, no necesitas separarlos en 2

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/index.html
> +    <footer>
el footer no necesita estar dentro de un article, no le aporta significado, así que podrías quitarlo.

2023-03-23 17:57 UTC, Alexis033 commented on student-cvs/andrssnsdc-4799/package.json
> +    "vite": "^4.2.1"
podrías poner vit como dependencia de desarrollo mejor.

2023-03-23 17:57 UTC, Alexis033 commented on student-forms/andrssnsdc-4799/src/scss/styles.scss
> +        padding: 0 8px;
Te falta agregarle un border radius a legend para que no se salga el color gris:
![image](https://user-images.githubusercontent.com/110948692/227295595-717eed64-f7f6-4bc4-9458-0b02db07dc27.png)

2023-03-28 14:52 UTC, Andrssnsdc commented on student-cvs/andrssnsdc-4799/package.json
> +    "vite": "^4.2.1"
vale ya la cambie a dependecia de desarrollo

2023-03-28 15:08 UTC, Andrssnsdc commented on student-forms/andrssnsdc-4799/src/scss/styles.scss
> +        padding: 0 8px;
ok ya agregue border radius gracias por la recomendacion visualmente se ve mejor

2023-05-30 16:14 UTC, Yanina-Unrein commented on student-blogs/andrssnsdc-4799/Layouts.html
> +<html lang="en">
fijarse que el idioma de la pagina coincida con el del html, cambiar por es ya que esta en español

2023-05-30 16:17 UTC, Yanina-Unrein commented on student-cvs/andrssnsdc-4799/Layouts.html
> +<html lang="en">
lo mismo acá

2023-05-30 16:18 UTC, Yanina-Unrein commented on student-cvs/andrssnsdc-4799/index.html
> +<html lang="en">
acá también

2023-05-30 16:19 UTC, Yanina-Unrein commented on student-forms/andrssnsdc-4799/src/index.html
> +<html lang="en">
fijarse lenguaje

2023-05-30 16:22 UTC, Yanina-Unrein approved these changes
dejo la revisión, por lo que veo un compañero ya realizo correcciones y las realizaste, es cierto que la estructura seria header, nav,main, section o article, footer.
En section o article englobar el mismo tema.
solo fíjate lo del idioma, ya están aplicados los cambios por lo que veo, suerte!

2023-06-01 02:32 UTC, Arzeus17 approved these changes

2023-06-14 02:24 UTC, Andrssnsdc commented
✌️

2023-06-14 02:55 UTC, merged