Pull Request semana 3
undefined-academy/semana-3 pull request #45
Opened 2023-03-28 01:28 UTC by cramdal

## Pull Request semana 3 ##
1. Layout para el blog
2. Mobile First para el CV
3. Agregar estructura moderna js para el CV
4. Formulario bootstrap

2023-03-28 10:35 UTC, aitorias requested changes

2023-03-28 10:35 UTC, aitorias commented on student-blogs/DaliaCR-5299/style.css
Estaría bien si pudieras diseñar, o bien en responsive  o con _mobile first_, las tarjetas para que se pudieran ver bien en distintos dispositivos haciendo uso de **`@media`**

![image](https://user-images.githubusercontent.com/6051056/228204732-7be34216-6313-43f0-9d3f-82d369db597f.png)

2023-03-28 10:35 UTC, aitorias commented on student-cvs/DaliaCR-5299/index.html
Muy limpito y lindo el diseño! 😋 En cuanto a código, lo estructuraría un pelín mejor ya que visualmente no está muy bien "indentado".

2023-03-28 10:35 UTC, aitorias commented on student-cvs/DaliaCR-5299/styles.css
> +pre {
Tienes dos selectores `pre` en el archivo CSS. Podrías colocar estos estilos en el mismo selector de arriba.

2023-03-28 10:35 UTC, aitorias commented on student-forms/DaliaCR-5299/src/index.html
Funciona perfectamente Bootstrap con Vite! Lo único que vi, como apreciaciones personales, pondría algo de separación antes del título **Contacto** respecto la barra de menú superior, y le daría una vuelta de diseño en los `input[type="radio"]` ya que no queda muy claro en diseño respecto a los otros `input`. Por lo demás genial! 😄 

![image](https://user-images.githubusercontent.com/6051056/228209224-36049770-f213-4614-8975-72e150ba1dab.png)

2023-03-29 01:58 UTC, cramdal commented on student-forms/DaliaCR-5299/src/index.html
Hola, hice algunas mejoras que me indicaste. Eres tan amable de volver a revisar, por favor. Gracias

2023-03-29 08:06 UTC, aitorias approved these changes
Los cambios funcionaron perfectamente. Quedó muy bonito! 😄

2023-03-29 08:06 UTC, aitorias commented on student-cvs/DaliaCR-5299/styles.css
> +  .rb {
Ahora los `input[type="radio]` quedan más claro que van juntos! 😋  Lo único que esta clase hace que para pantallas de resolución superior a 992px no se muestren los radio (no sé si está hecho a propósito)

2023-03-29 08:06 UTC, aitorias commented on student-forms/DaliaCR-5299/src/index.html
Ahora está genial! 😃 Muy lindo!

2023-04-05 00:12 UTC, 4ngelo12 approved these changes
Te quedo bien.

2023-04-07 00:28 UTC, merged