cards .html + estilo con .css
undefined-academy/semana-3 pull request #51
Opened 2023-03-29 01:11 UTC by truquinio

**1ro** Fork del repo de Undefined-Academy-semana3
**2do** Francia
**3ro** Se creó el .html semántico  + estilos .css + reset css
**4to** Creé otra vista con tarjetas (cards) y apliqué propiedad FLEX en .css
**5to** Hice commit de los cambios
**6to** Creé esta pull request

2023-03-31 21:24 UTC, truquinio commented
**7mo** Dentro de 'student-cvs' creé index.html, styles.css intercalando Flexbox y CSS Grid
**8vo** Dentro de 'student-form' creé form.html, form.css intercalando Flexbox y CSS Grid
**9no** Dentro de 'student-blog' creé cards.html, cards.css intercalando Flexbox y CSS Grid
**10°** Adapté todos los estilos a Mobile-First y luego a Desktop
**11°** Agregué vite como dependencia con `npm install vite`
**12°** Agregué en el package.json los scripts de vite
**13°** Agregué el primer archivo de JavaScript `<script type="module" src="/main.mjs"></script>`
**14°** Uso Bootstrap
**15°** Commit

2023-03-31 22:40 UTC, truquinio commented
**7mo** Dentro de 'student-cvs' creé index.html, styles.css
**8vo** Dentro de 'student-form' creé form.html, form.css
**9no** Dentro de 'student-blog' creé cards.html, cards.css
**10°** Adapté todos los estilos a Mobile-First y luego a Desktop
**11°** Agregué vite como dependencia con `npm install vite`
**12°** Agregué en el package.json los scripts de vite
**13°** Agregué el primer archivo de JavaScript `<script type="module" src="/main.mjs"></script>`
**14°** Uso Bootstrap
**15°** Commit

2023-04-03 15:32 UTC, truquinio commented
> 

Porque al principio quería que la navegación por la página fuera "realista" y al usar la barra de nav el usuario pudiera ir entrando en cada vista. Pero después me di cuenta que debía correr un `npx vite dev` por c/u y yo pensaba que era por la ubicación de los html. Y quedó así xD

2023-04-03 15:38 UTC, marisolSv22 approved these changes

2023-04-04 00:14 UTC, MariaSolArroyo approved these changes
Lo veo muy completo, si hay algo para corregir se me paso pero cumple lo que pedían. 😃

2023-04-04 01:17 UTC, truquinio commented
> Lo veo muy completo, si hay algo para corregir se me paso pero cumple lo que pedían. 😃

Muchísimas gracias María Sol!!

2023-04-04 13:13 UTC, dfm555 requested changes
@truquinio debes revisar tu estructura de carpetas, estás no cumplen con el ejercicio.

2023-05-18 02:20 UTC, closed without merging