Exercises Week 3 - Responsive and UI Frameworks
undefined-academy/semana-3 pull request #53
Opened 2023-03-29 05:23 UTC by pablo-alex

# Week 3 Exercise

- Forked the repository to my github
- Cloned the repository to my local directory  

## Week 3 - Flex and Grid
- Create a directory with my discord user name
- Create a HTML and styles files, the goal is built a blod page and use grid and flex techniques
- Commit and push the changes
- Create a new PR

2023-03-29 05:27 UTC, pablo-alex commented
## Week 3 - Responsive Design
- Create a directory with my discord user name
- Update the previous CV hmtl page that we made in the last week and use responsive techniques to be able to have a mobile view
- Use media queries in our style file
- Commit and push the changes
- Create a new PR

2023-03-29 05:30 UTC, pablo-alex commented
## Week 3 -Frameworks UI
- Create a directory with my discord user name
- Init our project with npm and add Vite dependency
- Add the settings in order to have Vite working (Update package json and add vite.config.js)
- Add the bootstrap dependency and sass
- Update the contact html document in order now using the bootstrap classes
- Commit and push the changes
- Create a new PR

2023-03-29 16:03 UTC, JoseCamilo84 requested changes

2023-03-29 16:03 UTC, JoseCamilo84 commented on student-forms/PabloXD-4695/bootstrap/src/scripts/main.js
> +
Hola, creo que esos import estan de más, ya que no los necesitas dentro del archivo js

2023-03-29 16:12 UTC, JoseCamilo84 requested changes

2023-03-29 16:12 UTC, JoseCamilo84 commented on student-cvs/PabloXD-4695/index.html
> +          <div class="nav-item">Home</div>
Hola el menu lo podrias envolver en una etiqueta "nav" luego usar la etiqueta "ul" y dentro cada una de las opciones serían "li" y dentro de cada "li" una etiqueta "a"

2023-03-29 16:13 UTC, JoseCamilo84 commented on student-cvs/PabloXD-4695/index.html
> +          <div class="nav-item">Home</div>
Hola, ayúdame también revisando el mío, gracias

2023-03-29 18:21 UTC, pablo-alex commented on student-forms/PabloXD-4695/bootstrap/src/scripts/main.js
> +
Correcto el segundo import no es necesario, ya elimando el primero tendria problemas con el bootstrap.

2023-03-29 18:21 UTC, pablo-alex commented on student-cvs/PabloXD-4695/index.html
> +          <div class="nav-item">Home</div>
Aplique las sugerencias gracias

2023-03-29 22:05 UTC, JoseCamilo84 approved these changes

2023-04-06 15:41 UTC, MauBedoya approved these changes
Todo parece correcto 👌
solo un detalle en la forma de acomodar algunas secciones para la version móvil

2023-04-06 15:41 UTC, MauBedoya commented on student-cvs/PabloXD-4695/index.html
> +          <h2>Skills</h2>
en esta sección y las de la imagen podria estar bien usar dos o 3 columnas con grid o flex con wrap para que se acomoden mejor las cosas en la version móvil.
![image](https://user-images.githubusercontent.com/111880575/230427846-fbb9da51-4f45-4cd8-95f6-be43b9483058.png)

2023-04-06 20:15 UTC, pablo-alex commented on student-cvs/PabloXD-4695/index.html
> +          <h2>Skills</h2>
Hola @MauBedoya gracias por tu revision, muy cierto no habia fijado bien esa parte en la version movil aplicare tu sugerencia.

2023-04-07 00:28 UTC, merged