adiciono CV, Blog y Form de Yessy-2278
undefined-academy/semana-3 pull request #58
Opened 2023-03-30 23:29 UTC by ycastaneda1

2023-05-04 13:45 UTC, camilasilvab approved these changes
Esta todo bien, lo único como sugerencia es separar las imágenes en una carpeta por aquello de la organización.

2023-05-05 21:25 UTC, MrRedu requested changes
### Observaciones:

**Blog:** 
- Todo bien, todo bien

**CV:**
- En HTML, existen las tablas como tal. En el apartado de los comandos para Linux, considero que quedaría más adecuado poner tablas del mismo HTML (https://www.htmlquick.com/es/tutorials/tables.html)

**Form:**
- Los inputs no tienen el atributo "required" para ser necesarios. Básicamente se pueden enviar los formularios vacíos.
- No encuentro el archivo de JavaScript donde se previene el comportamiento prefeterminado del envío del formulario. Para hacer esto, puedes ir al README.md del repositorio y salen los pasos.
> (sumarle esto también) Debes crear un archivo `.mjs`, y por consiguiente agregar `"module":"module"`, en el package.json, después de la línea `main`

<br>

_El perrito se ganó mi corazón._

2023-05-05 21:25 UTC, MrRedu commented on student-forms/Yessy-2278/Bootstrap/package.json
> +  "scripts": {
Para la semana 3, se agregan estos scripts. Están en el readme.md del repositorio, pero la verdad no son necesarios para correr el proyecto.
```
{
    "scripts": {
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
    }
}
```

2023-05-05 21:25 UTC, MrRedu commented on student-forms/Yessy-2278/Bootstrap/src/index.html
> +<html lang="en">
Como el contenido está en español, podrías poner `es`, en vez de `en`, en el _atributo_ `lang`, de la etiqueta `html`. Es para cambiar el idioma de la página entre **_english y español_**

2023-05-05 21:25 UTC, MrRedu commented on student-forms/Yessy-2278/Bootstrap/src/index.html
> +          <input type="text" class="form-control" placeholder="Nombres" aria-label="Nombres">
Faltaron los `required` en los `input`, como mencioné en la observación general

2023-05-05 21:25 UTC, MrRedu commented on student-cvs/Yessy-2278/index.html
> +    <Section class="InfAdicional">
Observación, las etiquetas siempre van en minúscula, y el nombre de las clases deben comenzar con minúscula también, se conoce como nomenclatura **`camelCase`**

2023-05-17 01:07 UTC, ycastaneda1 commented
@MrRedu ya está todo para tu approval. Gracias!

2023-05-17 01:19 UTC, MrRedu approved these changes
### ¡Buen trabajo! 💪🏼

2023-05-20 11:35 UTC, merged