Finally I did it.
undefined-academy/semana-3 pull request #76
Opened 2023-04-04 22:33 UTC by Josofico

# Take me a while

This exercises were so interesting and take a while to understand, I'm waiting for more in week 4.

2023-04-14 04:29 UTC, Lealdos requested changes
## You need to delete some files please

2023-04-14 04:29 UTC, Lealdos commented on student-cvs/Kick-Off-2479/package-lock.json
# Delete file
This file is not necessary on the remote repository, add it to your git ignore, please.

2023-04-14 04:29 UTC, Lealdos commented on student-forms/Kick-Off-2479/bootstrap-setup/package-lock.json
# Delete file from  the remote

2023-04-14 04:29 UTC, Lealdos commented on student-forms/Kick-Off-2479/bootstrap-setup/package.json
> +    "sass": "^1.60.0",
# Correct sass location in the file
Sass suppose to be in dependence not in devdependence

2023-04-14 12:29 UTC, Lmendev commented on student-cvs/Kick-Off-2479/package-lock.json
No. 

[Está bien que lo agregue.](https://www.ictshore.com/javascript/package-lock-json-source-control/)

2023-04-14 12:34 UTC, Lmendev approved these changes

2023-04-17 18:19 UTC, Lealdos approved these changes

2023-04-17 20:56 UTC, merged