Actividad semana 3
undefined-academy/semana-3 pull request #8
Opened 2023-03-23 03:09 UTC by Alexis033

Se añade cv responsive, formulario con tailwind y blog con grid y flex.

2023-03-23 19:20 UTC, dfm555 requested changes
@Alexis033 resuelve conflictos en .gitignore

2023-03-23 19:57 UTC, Alexis033 commented
> @Alexis033 resuelve conflictos en .gitignore

Listo, gracias, arreglado.

2023-03-24 18:42 UTC, MauBedoya approved these changes
Parece que se cumple con lo pedido en las clases, te deje unos cuantos comentarios para aclarar algunas cosas, y también sería bueno que despliegues tu CV en un lugar como [GitHub Pages](https://pages.github.com/) o algún otro para facilitar la revision y que se puedan ver las imágenes sin necesidad de descargar todos los archivos, esto también ayudaría a ver bien como se ve en un móvil real supongo 🤔.

2023-03-24 18:42 UTC, MauBedoya commented on student-cvs/Maikcol-2796/main.mjs
> +const navButton= document.querySelector('.nav-button')
tengo entendido que se suele usar "$" en los nombres de constantes que almacenan elementos del DOM, tal que asi:
```js
const $navButton = document.querySelector('.nav-button')
```
Creo que no es obligatorio pero entiendo que sirve para distinguir mas fácil estas de otras variables que no contengan elementos 🤔

2023-03-24 18:42 UTC, MauBedoya commented on student-cvs/Maikcol-2796/index.html
> +                <h1 class="section-title">Hi, I'm Maikcol Guevara.</h1>
aquí me parece que al darse el efecto de "typewriter" en pantallas con anchos menores a 390px, como el s8 y s9+ (del modo desarrollar de Edge), el contendor de ese texto se ensancha y provoca que se dé un "overflow" en el eje horizontal.
Pero esto no estoy del todo seguro si pasaría en un dispositivo real o si es un bug o algo así del modo desarrollador de Edge 😅, de cualquier forma, quizá seria bueno disminuir un poco la `font-size` para evitar cualquier problema.

2023-03-24 18:42 UTC, MauBedoya commented on student-cvs/Maikcol-2796/style.css
> +  /* .project__description{
aquí es más una duda, hiciste primero la version "mobile first" de tu CV? porque este breakpoint indicaría que cambiaste el diseño a partir de la version de desktop, verdad? 🤔

2023-03-24 18:51 UTC, Alexis033 commented on student-cvs/Maikcol-2796/index.html
> +                <h1 class="section-title">Hi, I'm Maikcol Guevara.</h1>
mm la verdad no sé, cuando lo pruebo se ve bien, pero claro cuando lo despliegue reviso realmente como queda en un dispositivo movil:
![image](https://user-images.githubusercontent.com/110948692/227614057-f0baa7ed-0c9a-4d8d-800c-82b18963dd15.png)

2023-03-24 19:01 UTC, Alexis033 commented on student-cvs/Maikcol-2796/main.mjs
> +
Sí, había pensado en agregar algo así, pero iba a hacerlo cuando pasáramos a react con algún estado, pero megusta tu solución, gracias.

2023-03-24 19:04 UTC, Alexis033 commented on student-cvs/Maikcol-2796/main.mjs
> +const navButton= document.querySelector('.nav-button')
Es cierto, es una buena practica, lo voy a cambiar, gracias.

2023-03-24 19:07 UTC, Alexis033 commented
> 
Gracias por la revisión, había pensado en desplegarla cuando estuviera un poco más trabajada, pero voy a intentar hacerlo para la próxima entrega.

2023-03-24 21:25 UTC, MauBedoya commented on student-cvs/Maikcol-2796/index.html
> +                <h1 class="section-title">Hi, I'm Maikcol Guevara.</h1>
mmm si la verdad un poco raro, creo que en el caso de pantallas de 360 funciona bien si se sale y entra de las herramientas de desarrollador (en el caso de Edge), creo que más que nada con las pantallas aún más angostas como esta:

![image](https://user-images.githubusercontent.com/111880575/227638111-4788463f-fe4b-4861-926d-8b6cdaf5d754.png)

2023-03-28 23:41 UTC, dfm555 approved these changes

2023-03-28 23:41 UTC, merged