Semana 3 completada
undefined-academy/semana-3 pull request #90
Opened 2023-04-06 21:40 UTC by marcospenalosa

Añado los ejercicios de la semana 3

2023-04-07 12:35 UTC, EvanaSabatella1989 approved these changes

2023-04-07 12:35 UTC, EvanaSabatella1989 commented on student-cvs/murquis-5340/styles.css
> +}
Excelente tu trabajo Marcos, aquí podrías agregar otro punto de quiebre.

2023-04-07 12:35 UTC, EvanaSabatella1989 commented on student-forms/murquis-5340/src/index.html
> +
y este formulario puede tener más ítems. Espero que veas mi Repo también :) Sigue así, muchos éxitos.

2023-04-09 20:09 UTC, marcospenalosa commented on student-forms/murquis-5340/src/index.html
> +
El poco tiempo del que dispongo me lleva a optimizar al máximo 😅 gracias!

2023-04-09 20:42 UTC, MauBedoya requested changes
Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR.
Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)

2023-04-10 19:12 UTC, marcospenalosa commented
> Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR. Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)

Lo eliminé para que no sobrescribiera el principal de undefined-academy, puesto que tuve que añadir una línea de código para que no importara los node_modules ``` /student-forms/murquis-5340/node_modules ```

No creo que se deba de añadir por ese motivo.

2023-04-10 23:35 UTC, MauBedoya commented
> > Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR. Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)
> 
> Lo eliminé para que no sobrescribiera el principal de undefined-academy, puesto que tuve que añadir una línea de código para que no importara los node_modules `/student-forms/murquis-5340/node_modules`
> 
> No creo que se deba de añadir por ese motivo.

mmm pero si eliminas el `.gitignore` de tu carpeta clonada y subes ese "cambio", se elimina el .gitignore principal que dices no querer sobrescribir (o eso tengo entendido (?👀).
Podrías hacer la prueba a configurar un '.gitignore_global' que ignorara esa carpeta de todos tus repos y así te olvidas del .gitignore.
En mi caso lo hice así:
```
cd ~
touch .gitignore_global
code .gitignore_global   (pones el contenido que quieres que se ignore, en tu caso el `node_modules`)
git config --global core.excludesfile ~/.gitignore_global 
```
Y creo que con eso la próxima que abras tu VSC ya no debería subirse tu node_modules.

2023-04-11 14:01 UTC, marcospenalosa commented
> > > Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR. Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)
> > 
> > 
> > Lo eliminé para que no sobrescribiera el principal de undefined-academy, puesto que tuve que añadir una línea de código para que no importara los node_modules `/student-forms/murquis-5340/node_modules`
> > No creo que se deba de añadir por ese motivo.
> 
> mmm pero si eliminas el `.gitignore` de tu carpeta clonada y subes ese "cambio", se elimina el .gitignore principal que dices no querer sobrescribir (o eso tengo entendido (?👀). Podrías hacer la prueba a configurar un `.gitignore_global` que ignorara esa carpeta de todos tus repos y así te olvidas del .gitignore. En mi caso lo hice así:
> 
> ```
> cd ~
> touch .gitignore_global
> code .gitignore_global   (pones el contenido que quieres que se ignore, en tu caso el `node_modules`)
> git config --global core.excludesfile ~/.gitignore_global 
> ```
> 
> Y creo que con eso la próxima que abras tu VSC ya no debería subirse tu node_modules.

Añadido .gitignore

2023-04-12 14:55 UTC, MauBedoya commented
> > > > Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR. Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)
> > > 
> > > 
> > > Lo eliminé para que no sobrescribiera el principal de undefined-academy, puesto que tuve que añadir una línea de código para que no importara los node_modules `/student-forms/murquis-5340/node_modules`
> > > No creo que se deba de añadir por ese motivo.
> > 
> > 
> > mmm pero si eliminas el `.gitignore` de tu carpeta clonada y subes ese "cambio", se elimina el .gitignore principal que dices no querer sobrescribir (o eso tengo entendido (?👀). Podrías hacer la prueba a configurar un `.gitignore_global` que ignorara esa carpeta de todos tus repos y así te olvidas del .gitignore. En mi caso lo hice así:
> > ```
> > cd ~
> > touch .gitignore_global
> > code .gitignore_global   (pones el contenido que quieres que se ignore, en tu caso el `node_modules`)
> > git config --global core.excludesfile ~/.gitignore_global 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Y creo que con eso la próxima que abras tu VSC ya no debería subirse tu node_modules.
> 
> Añadido .gitignore

Hiciste el pull para traerte el `.gitignore` original y así no sobrescribir nada?
por qué parece que sigues con conflicto de rama: 
![image](https://user-images.githubusercontent.com/111880575/231497258-b872bcdc-2c17-444a-a37c-810667f1b42c.png)

2023-04-13 17:35 UTC, marcospenalosa commented
Acabo de hacer un pull (el cual me obligó a un merge porque estaban con conflicto) y después un gitpush y sigue igual, el pull se puede hacer igualmente, porque lo que harán es que prevalezca el .gitignore de undefined.

2023-04-14 20:33 UTC, MauBedoya commented
> 

mmm es que veo él ".gitignore" que estas tratando de subir y sigue marcado como modificado y solo tiene 24 líneas mientras que él .gitignore original tiene casi 400, cuando te decía pull me refería a actualizar tu repositorio local con `git pull origin main`
para que se traiga el archivo original y luego hacer un commit nuevo para que concuerden los archivos, o no se si me estoy confundiendo 😅

2023-04-14 20:34 UTC, marcospenalosa commented
> > > > > Te quedo bastante bien el responsive de tu CV 👍, ahora sería ir trabajando en el responsive de tu blog para el siguiente PR. Solo resuelve el conflicto de ramas antes de poder darle la aprobación (parece que borraste el `.gitignore`)
> > > > 
> > > > 
> > > > Lo eliminé para que no sobrescribiera el principal de undefined-academy, puesto que tuve que añadir una línea de código para que no importara los node_modules `/student-forms/murquis-5340/node_modules`
> > > > No creo que se deba de añadir por ese motivo.
> > > 
> > > 
> > > mmm pero si eliminas el `.gitignore` de tu carpeta clonada y subes ese "cambio", se elimina el .gitignore principal que dices no querer sobrescribir (o eso tengo entendido (?👀). Podrías hacer la prueba a configurar un `.gitignore_global` que ignorara esa carpeta de todos tus repos y así te olvidas del .gitignore. En mi caso lo hice así:
> > > ```
> > > cd ~
> > > touch .gitignore_global
> > > code .gitignore_global   (pones el contenido que quieres que se ignore, en tu caso el `node_modules`)
> > > git config --global core.excludesfile ~/.gitignore_global 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Y creo que con eso la próxima que abras tu VSC ya no debería subirse tu node_modules.
> > 
> > 
> > Añadido .gitignore
> 
> Hiciste el pull para traerte el `.gitignore` original y así no sobrescribir nada? por qué parece que sigues con conflicto de rama: ![image](https://user-images.githubusercontent.com/111880575/231497258-b872bcdc-2c17-444a-a37c-810667f1b42c.png)

Ya no hay conflictos! 😅

2023-04-14 20:57 UTC, MauBedoya approved these changes

2023-04-16 03:18 UTC, merged